<AnalyseCompost>
    id: my_widget
    orientation: 'vertical'


    BoxLayout:

        orientation : "vertical"
        size: root.width, root.height
        Button:
            text: 'Scanner un fruit'
            on_press: root.scan_fruit()
        Image:
            id: my_image
            source: ""

        FileChooserListView:
            id: filechooser
            on_selection: my_widget.selected(filechooser.selection)